#!/bin/bash 

ID=$(id -u)

TIMESTAMP=$(date +%F-%m-%S)

LOGFILE=/tmp/$0-$TIMESTAMP.log

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

validation(){

    if [ $1 -ne 0 ]
then 
    echo -e "$R $2 ...........failed $N"
else
    echo -e "$G $2............success $N"

fi
}

if [ $ID -ne 0 ]
then 
    echo -e " $R please run this script with root user $N"
    exit 1
else
    echo -e "$G you're a root user $N"

    dnf install nginx -y
    validation $? "installing nginx"

    systemctl enable nginx
    validation $? "enableing nginx"

    systemctl start nginx
    validation $? "starting nginx"

    rm -rf /usr/share/nginx/html/*
    validation $? "removing nginx tmp files "

    curl -o /tmp/web.zip https://roboshop-builds.s3.amazonaws.com/web.zip
    validation $? "robocode "

    cd /usr/share/nginx/html
    validation $? "changing directory"

    unzip /tmp/web.zip
    validation $? "unziping"

    cp /home/centos/roboshell/roboshop.conf /etc/nginx/default.d/roboshop.conf 
    validation $? "copying config"

    systemctl restart nginx 
    validation $? "restart nginx"
fi






